"""Pydantic v2 schemas for the Recommendation domain."""
from datetime import datetime
from uuid import UUID

from pydantic import BaseModel, ConfigDict

from app.api.schemas.opportunity_schema import OpportunityRead


class RecommendationRead(BaseModel):
    """Schema returned to clients for a single scored recommendation.

    Embeds a fully populated :class:`OpportunityRead` object alongside
    the computed score and the human-readable ``match_reasons`` list
    generated by :class:`AgentAdvisor`.
    """

    model_config = ConfigDict(from_attributes=True)

    recommendation_id: UUID
    score: float
    match_reasons: list[str]
    opportunity: OpportunityRead
    created_at: datetime


class RecommendationRequest(BaseModel):
    """Schema for requesting a personalised top-N recommendation list.

    ``top_n`` controls the maximum number of recommendations returned.
    Defaults to 10 when not provided by the caller.
    """

    model_config = ConfigDict(from_attributes=True)

    top_n: int = 10
