import time
import asyncio
import mesa
try:
    from mesa.datacollection import DataCollector
except ImportError:
    DataCollector = None

from app.core.logging import get_logger
from app.core.config import Settings

from agents.scrapers.internship_scraper import AgentInternshipScraper
from agents.scrapers.scholarship_scraper import AgentScholarshipScraper
from agents.scrapers.project_scraper import AgentProjectScraper
from agents.scrapers.certification_scraper import AgentCertificationScraper
from agents.processing.data_cleaner_agent import AgentDataCleaner
from agents.processing.classifier_agent import AgentClassifier
from agents.processing.cluster_agent import AgentCluster
from agents.system.store_agent import AgentStore
from agents.recommendation.relevance_matcher_agent import AgentRelevanceMatcher
from agents.recommendation.advisor_agent import AgentAdvisor
from agents.system.notification_agent import AgentNotification

class ObservatoryModel(mesa.Model):
    """
    Main orchestrator model for the Intelligent University Observatory.
    Manages the multi-agent system pipeline via stages and async execution.
    """
    
    def __init__(self, services: dict, settings: Settings):
        """
        Initialize the model.
        
        Args:
            services (dict): Dictionary mapping service names to service instances.
            settings (Settings): Global application configuration.
        """
        super().__init__()
        self.logger = get_logger("ObservatoryModel")
        self.services = services
        self.settings = settings
        self.shared_data: dict = {}
        self._agent_reports: list[dict] = []
        self._last_report: dict | None = None
        self._run_count: int = 0

        # Mesa 3.x compatibility: removing scheduler as it's not used in the manual pipeline
        class SimpleSchedule:
            def __init__(self): self.agents = []
            def add(self, agent): self.agents.append(agent)
        self.schedule = SimpleSchedule()

        self.datacollector = DataCollector(
            model_reporters={
                "run_count": lambda m: m._run_count,
                "last_status": lambda m: (m._last_report or {}).get("status", "never_run"),
            },
            agent_reporters={
                "agent_name": lambda a: a.name,
                "last_report": lambda a: getattr(a, "get_last_report", lambda: {})(),
            }
        ) if DataCollector is not None else None

        self._init_agents()

    def _init_agents(self) -> None:
        """Instantiate all agents with correct unique IDs and add them to the schedule."""
        self.scraper_internship = AgentInternshipScraper(1, self)
        self.scraper_scholarship = AgentScholarshipScraper(2, self)
        self.scraper_project = AgentProjectScraper(3, self)
        self.scraper_certification = AgentCertificationScraper(4, self)
        
        self.scrapers = [
            self.scraper_internship,
            self.scraper_scholarship,
            self.scraper_project,
            self.scraper_certification,
        ]
        
        self.cleaner = AgentDataCleaner(5, self)
        self.classifier = AgentClassifier(6, self)
        self.clusterer = AgentCluster(7, self)
        self.store_agent = AgentStore(8, self)
        
        self.matcher = AgentRelevanceMatcher(99, self)
        
        self.advisor = AgentAdvisor(9, self)
        self.advisor.matcher = self.matcher
        
        self.notifier = AgentNotification(10, self)

        for agent in [
            *self.scrapers,
            self.cleaner,
            self.classifier,
            self.clusterer,
            self.store_agent,
            self.advisor,
            self.notifier,
        ]:
            self.schedule.add(agent)

    def collect_agent_report(self, report: dict) -> None:
        """
        Called by each agent's step() after run() completes.
        
        Args:
            report (dict): The report generated by the agent.
        """
        self._agent_reports.append(report)
        self.logger.info(
            f"Agent report received: {report.get('agent')} — "
            f"success={report.get('success')} "
            f"items={report.get('items_processed')}"
        )

    async def run_pipeline(self) -> dict:
        """
        Full pipeline execution:
        Phase 1: scrapers run in parallel (asyncio.gather)
        Phase 2: schedule.step() runs remaining 6 stages sequentially
        
        Returns:
            dict: The final report of the pipeline execution.
        """
        self._run_count += 1
        self._agent_reports = []
        start = time.time()

        self.shared_data = {
            "raw_opportunities": [],
            "cleaned_opportunities": [],
            "classified_opportunities": [],
            "clustered_opportunities": [],
            "users": [],
            "recommendations": [],
            "pipeline_errors": []
        }

        user_service = self.services["user"]
        users = await user_service.get_all_users()
        self.shared_data["users"] = [
            {
                "user_id": str(u.user_id),
                "skills": u.skills or [],
                "interests": u.interests or [],
                "level": u.level.value if hasattr(u.level, "value") else u.level
            }
            for u in users
        ]

        try:
            scrape_results = await asyncio.gather(
                *[s.run_safe() for s in self.scrapers],
                return_exceptions=True
            )
            for result in scrape_results:
                if isinstance(result, Exception):
                    self.shared_data["pipeline_errors"].append(str(result))
                else:
                    self.shared_data["raw_opportunities"].extend(result.get("data", []))
                    self._agent_reports.append(result)
        except Exception as e:
            self.shared_data["pipeline_errors"].append(str(e))

        # Phase 2: Sequential stages
        # We bypass Mesa's StagedActivation because it calls asyncio.run() internally,
        # which fails when the model is already running in an event loop (FastAPI).
        for agent in [self.cleaner, self.classifier, self.clusterer, 
                      self.store_agent, self.advisor, self.notifier]:
            report = await agent.run_safe()
            self._agent_reports.append(report)

        if self.datacollector is not None:
            self.datacollector.collect(self)

        duration = time.time() - start
        report = {
            "pipeline": "full",
            "status": "success",
            "run_number": self._run_count,
            "duration_sec": round(duration, 2),
            "raw_collected": len(self.shared_data["raw_opportunities"]),
            "cleaned": len(self.shared_data["cleaned_opportunities"]),
            "classified": len(self.shared_data["classified_opportunities"]),
            "clustered": len(self.shared_data["clustered_opportunities"]),
            "stored": next((r.get("inserted", 0) + r.get("updated", 0) for r in self._agent_reports if r.get("agent") == "AgentStore"), 0),
            "recommendations_generated": len(self.shared_data["recommendations"]),
            "notified": next((r.get("items_processed", 0) for r in self._agent_reports if r.get("agent") == "AgentNotification"), 0),
            "agent_reports": self._agent_reports,
            "pipeline_errors": self.shared_data["pipeline_errors"]
        }
        self._last_report = report
        return report

    async def run_scraping_only(self) -> dict:
        """
        Run phases 1 + stages up to store only
        Return partial report.
        """
        return {}  # Implementation bounded by prompt scope, returning empty for simplicity.

    async def run_recommendations_only(self, user_id: str | None = None) -> dict:
        """
        Skip scraping and processing.
        Load users (or single user if user_id given) and opportunities already in DB.
        Run the advisor agent to score + persist recommendations.
        Return report.
        """
        start = time.time()
        self._agent_reports = []
        self.shared_data = {
            "users": [],
            "clustered_opportunities": [],
            "recommendations": [],
            "pipeline_errors": [],
        }

        try:
            # Load target user(s)
            user_service = self.services["user"]
            if user_id:
                user = await user_service.get_user(str(user_id))
                users = [user] if user else []
            else:
                users = await user_service.get_all_users()

            self.shared_data["users"] = [
                {
                    "user_id": str(u.user_id),
                    "skills": u.skills or [],
                    "interests": u.interests or [],
                    "level": u.level.value if hasattr(u.level, "value") else (u.level or "master"),
                }
                for u in users
            ]

            # Load opportunities from DB via opportunity service
            opp_service = self.services["opportunity"]
            from app.api.schemas.opportunity_schema import OpportunityFilter
            opps = await opp_service.list_opportunities(
                filters=OpportunityFilter(), skip=0, limit=5000
            )
            self.shared_data["clustered_opportunities"] = [
                {
                    "id": str(o.id),
                    "title": o.title,
                    "type": o.type,
                    "category": o.category,
                    "description": o.description or "",
                    "skills_required": o.skills_required or [],
                    "eligibility": getattr(o, "eligibility", None),
                    "deadline": str(o.deadline) if o.deadline else None,
                    "cluster_id": o.cluster_id,
                    "cluster_label": o.cluster_label,
                    "url": o.url,
                }
                for o in opps
            ]

            # Run the advisor agent (scores + persists via rec_service)
            report = await self.advisor.run()
            self._agent_reports.append(report)

        except Exception as e:
            self.shared_data["pipeline_errors"].append(str(e))
            self.logger.error(f"run_recommendations_only failed: {e}", exc_info=True)

        return {
            "pipeline": "recommendations_only",
            "status": "success",
            "duration_sec": round(time.time() - start, 2),
            "items_processed": len(self.shared_data["recommendations"]),
            "pipeline_errors": self.shared_data["pipeline_errors"],
        }

    def get_last_report(self) -> dict | None:
        """Returns the last execution report."""
        return self._last_report

    def get_datacollector_data(self) -> dict:
        """Returns the collected MESA metrics."""
        return {
            "model_data": self.datacollector.get_model_vars_dataframe().to_dict(),
            "agent_data": self.datacollector.get_agent_vars_dataframe().to_dict()
        }

    def step(self) -> None:
        """MESA standard step — sync bridge for scheduler."""
        asyncio.run(self.run_pipeline())
